"""Plain-English health summaries, generated by Claude.

This lives on the backend rather than in the browser for one reason: the
Anthropic API is authenticated with a secret key. A key shipped in a Vite
bundle is readable by every visitor, and the API also refuses browser origins
unless explicitly opted in. Routing through here keeps the key server-side and
lets us cap length, enforce the wording rules, and cache by disease.
"""
from __future__ import annotations

import hashlib
import logging
from typing import Any

from fastapi import APIRouter, HTTPException, status
from pydantic import AliasChoices, BaseModel, ConfigDict, Field

from app.config import get_settings

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/summary", tags=["summary"])

# The user's spec named this model; it is a current, supported model id.
_MODEL = "claude-sonnet-4-6"
_MAX_TOKENS = 300

# Summaries are deterministic for a given input, so an in-process cache spares
# both latency and spend. Bounded so a long-running dyno cannot grow unbounded.
_CACHE: dict[str, str] = {}
_CACHE_MAX = 500

_SYSTEM = (
    "You are a nutrition science communicator writing for a general audience. "
    "You never claim that a food cures, treats or prevents disease. You write "
    "in plain language using hedged phrasing such as 'may support', 'evidence "
    "suggests' and 'associated with'. You never use bullet points or headings."
)


class SummaryRequest(BaseModel):
    """Both field spellings are accepted.

    The shipped frontend posts `top_foods` / `top_phytochemicals` / `top_genes`;
    the shorter `foods` / `phytochemicals` / `genes` are accepted as aliases so
    either client works and neither has to be redeployed in lockstep.
    """

    model_config = ConfigDict(populate_by_name=True)

    disease_name: str = Field(min_length=1, max_length=200)
    top_foods: list[str] = Field(
        default_factory=list,
        max_length=20,
        validation_alias=AliasChoices("top_foods", "foods"),
    )
    top_phytochemicals: list[str] = Field(
        default_factory=list,
        max_length=20,
        validation_alias=AliasChoices("top_phytochemicals", "phytochemicals"),
    )
    top_genes: list[str] = Field(
        default_factory=list,
        max_length=20,
        validation_alias=AliasChoices("top_genes", "genes"),
    )
    evidence_grade: str = Field(default="", max_length=40)


class SummaryResponse(BaseModel):
    summary: str
    model: str
    cached: bool = False


def _cache_key(req: SummaryRequest) -> str:
    parts = "|".join(
        [
            req.disease_name.lower().strip(),
            ",".join(req.top_foods[:5]).lower(),
            ",".join(req.top_phytochemicals[:3]).lower(),
            ",".join(req.top_genes[:3]).lower(),
            req.evidence_grade.lower(),
        ]
    )
    return hashlib.sha256(parts.encode("utf-8")).hexdigest()


def _build_prompt(req: SummaryRequest) -> str:
    return (
        "Write a 3-sentence plain English summary for a general audience about "
        f"how these plant foods may support {req.disease_name} management "
        "through their phytochemicals.\n\n"
        f"Top foods: {', '.join(req.top_foods[:5]) or 'not specified'}\n"
        f"Key phytochemicals: {', '.join(req.top_phytochemicals[:3]) or 'not specified'}\n"
        f"Gene targets: {', '.join(req.top_genes[:3]) or 'not specified'}\n"
        f"Evidence strength: {req.evidence_grade or 'mixed'}\n\n"
        "Write in simple language. Never claim cure or treatment. Use phrases "
        "like 'may support', 'evidence suggests', 'associated with'. Keep it "
        "under 80 words. No bullet points. Return only the summary text."
    )


@router.post(
    "",
    response_model=SummaryResponse,
    summary="Plain-English summary of a condition's food recommendations",
)
async def generate_summary(request: SummaryRequest) -> SummaryResponse:
    settings = get_settings()
    if not settings.anthropic_api_key:
        # 503 rather than 500: the deployment is missing a key, the request is fine.
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Summary generation is not configured on this deployment.",
        )

    key = _cache_key(request)
    cached = _CACHE.get(key)
    if cached:
        return SummaryResponse(summary=cached, model=_MODEL, cached=True)

    try:
        from anthropic import AsyncAnthropic
    except ImportError as exc:  # pragma: no cover - dependency is declared
        logger.error("anthropic SDK not installed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Summary generation is not available.",
        ) from exc

    client = AsyncAnthropic(api_key=settings.anthropic_api_key)

    try:
        message = await client.messages.create(
            model=_MODEL,
            max_tokens=_MAX_TOKENS,
            system=_SYSTEM,
            messages=[{"role": "user", "content": _build_prompt(request)}],
        )
    except Exception as exc:  # noqa: BLE001 - surface a clean error to the client
        logger.warning("Summary generation failed for %r: %s", request.disease_name, exc)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Could not generate a summary right now.",
        ) from exc

    # A safety classifier can decline; that is a 200 with stop_reason "refusal".
    if getattr(message, "stop_reason", None) == "refusal":
        logger.warning("Summary refused for %r", request.disease_name)
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Could not generate a summary for this condition.",
        )

    text = _first_text(message.content)
    if not text:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Could not generate a summary right now.",
        )

    if len(_CACHE) >= _CACHE_MAX:
        _CACHE.clear()
    _CACHE[key] = text

    return SummaryResponse(summary=text, model=_MODEL, cached=False)


def _first_text(content: list[Any]) -> str:
    """Concatenate the text blocks of a response, ignoring any other block type."""
    parts: list[str] = []
    for block in content or []:
        if getattr(block, "type", None) == "text":
            parts.append(getattr(block, "text", "") or "")
    return " ".join(p.strip() for p in parts if p.strip()).strip()
